describe('Test toast positions', () => {
  it('bottom-center render', () => {
    cy.visit('/')
    cy.get('#control-position').select('bottom-center')
    cy.visit('/iframe.html?viewMode=story&id=toast-from-button--toast-from-button&args=position:bottom-center')
    cy.get('[data-test-id=btn-error]').click()
    cy.get(`[data-test-id=error]`).should('be.visible')
    cy.get(`[data-test-id=error]`).parent().should('have.css', 'left')
    cy.get(`[data-test-id=error]`).parent().should('have.css', 'transform')
  })
  it('bottom-right render', () => {
    cy.visit('/')
    cy.get('#control-position').select('bottom-right')
    cy.visit('/iframe.html?viewMode=story&id=toast-from-button--toast-from-button&args=position:bottom-right')
    cy.get('[data-test-id=btn-error]').click()
    cy.get(`[data-test-id=error]`).should('be.visible')
    cy.get(`[data-test-id=error]`).parent().should('have.css', 'right', '10px')
    cy.get(`[data-test-id=error]`).parent().should('have.css', 'bottom', '10px')
  })
  it('top-right render', () => {
    cy.visit('/')
    cy.get('#control-position').select('bottom-right')
    cy.visit('/iframe.html?viewMode=story&id=toast-from-button--toast-from-button&args=position:top-right')
    cy.get('[data-test-id=btn-error]').click()
    cy.get(`[data-test-id=error]`).should('be.visible')
    cy.get(`[data-test-id=error]`).parent().should('have.css', 'right', '10px')
    cy.get(`[data-test-id=error]`).parent().should('have.css', 'top', '10px')
  })
  it('top-center render', () => {
    cy.visit('/')
    cy.get('#control-position').select('bottom-right')
    cy.visit('/iframe.html?viewMode=story&id=toast-from-button--toast-from-button&args=position:top-center')
    cy.get('[data-test-id=btn-error]').click()
    cy.get(`[data-test-id=error]`).should('be.visible')
    cy.get(`[data-test-id=error]`).parent().should('have.css', 'left')
    cy.get(`[data-test-id=error]`).parent().should('have.css', 'top', '10px')
    cy.get(`[data-test-id=error]`).parent().should('have.css', 'transform')
  })
  it('top-left render', () => {
    cy.visit('/')
    cy.get('#control-position').select('bottom-right')
    cy.visit('/iframe.html?viewMode=story&id=toast-from-button--toast-from-button&args=position:top-left')
    cy.get('[data-test-id=btn-error]').click()
    cy.get(`[data-test-id=error]`).should('be.visible')
    cy.get(`[data-test-id=error]`).parent().should('have.css', 'left', '10px')
    cy.get(`[data-test-id=error]`).parent().should('have.css', 'top', '10px')
  })
})